name: update eqim report
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - run: pip install -r requirements.txt
      - shell: bash
        env:
          atproto_username: ${{secrets.ATPROTO_USERNAME}}
          atproto_password: ${{secrets.ATPROTO_PASSWORD}}
          token: ${{ secrets.GH_PAT || github.token }}
        run: >
          python main.py --service default --username "$atproto_username" --password "$atproto_password" --gh-token "$token"
